import type { Property, Review } from "./types"

export const properties: Property[] = [
  {
    id: "1",
    name: "ANTIEQ Melati Residence",
    location: "Kota Gorontalo, Gorontalo",
    price: 600000,
    originalPrice: 900000,
    rating: 4.9,
    reviews: 85,
    image: "/images/antieq-exterior.jpg",
    images: [
      "/images/antieq-exterior.jpg",
      "/images/antieq-corridor.jpg",
      "/images/antieq-bedroom1.jpg",
      "/images/antieq-bathroom.jpg",
    ],
    facilities: ["WiFi 100Mbps", "AC Premium", "Kamar Mandi Dalam", "Parkir Luas", "CCTV 24/7"],
    available: 5,
    discount: "33%",
    isPopular: true,
    story: "Hunian eksklusif untuk putri di jantung Kota Gorontalo dengan akses mudah ke kampus dan pusat kota",
    description:
      "ANTIEQ Melati Residence adalah hunian premium khusus putri yang berlokasi strategis di pusat Kota Gorontalo. Dengan desain modern dan fasilitas lengkap, tempat ini menjadi pilihan utama mahasiswi dan pekerja muda.",
    type: "putri",
    coordinates: {
      lat: 0.5435,
      lng: 123.0582,
    },
    amenities: [
      "WiFi Fiber 100Mbps",
      "AC di setiap kamar",
      "Kamar mandi dalam",
      "Lemari pakaian",
      "Meja belajar",
      "Kasur spring bed",
      "Parkir motor",
      "CCTV 24 jam",
      "Security",
      "Dapur bersama",
      "Ruang tamu",
      "Laundry",
    ],
    rules: [
      "Khusus putri",
      "Tidak boleh membawa tamu lawan jenis ke kamar",
      "Jam malam 22:00 WIT",
      "Dilarang merokok",
      "Dilarang membawa hewan peliharaan",
      "Wajib menjaga kebersihan",
    ],
    contact: {
      phone: "+62 812-3456-7890",
      whatsapp: "+62 812-3456-7890",
      email: "melati@antieqkost.id",
    },
  },
  {
    id: "2",
    name: "ANTIEQ Harmoni Elite",
    location: "Limboto, Gorontalo",
    price: 450000,
    originalPrice: 650000,
    rating: 4.8,
    reviews: 62,
    image: "/images/antieq-evening-view.jpg",
    images: [
      "/images/antieq-evening-view.jpg",
      "/images/antieq-common-area.jpg",
      "/images/antieq-kitchen.jpg",
      "/images/antieq-community.jpg",
    ],
    facilities: ["WiFi Unlimited", "Dapur Bersama", "Laundry Gratis", "Security 24/7", "Mushola"],
    available: 8,
    discount: "31%",
    isPopular: false,
    story: "Konsep co-living modern untuk putra di area Limboto yang tenang dengan suasana kampung yang asri",
    description:
      "ANTIEQ Harmoni Elite menawarkan konsep co-living yang modern dengan suasana kekeluargaan. Berlokasi di Limboto yang tenang, cocok untuk mahasiswa dan pekerja yang menginginkan lingkungan kondusif.",
    type: "putra",
    coordinates: {
      lat: 0.6089,
      lng: 123.0107,
    },
    amenities: [
      "WiFi unlimited",
      "Dapur bersama lengkap",
      "Laundry gratis",
      "Mushola",
      "Ruang santai",
      "Parkir luas",
      "Security 24 jam",
      "Air mineral",
      "Cleaning service",
      "Coworking space",
    ],
    rules: [
      "Khusus putra",
      "Jam berkunjung tamu sampai 21:00 WIT",
      "Dilarang membawa alkohol",
      "Wajib menjaga ketenangan",
      "Gotong royong kebersihan",
      "Respect sesama penghuni",
    ],
    contact: {
      phone: "+62 812-3456-7891",
      whatsapp: "+62 812-3456-7891",
      email: "harmoni@antieqkost.id",
    },
  },
  {
    id: "3",
    name: "ANTIEQ Luxury Suites",
    location: "Bone Bolango, Gorontalo",
    price: 800000,
    originalPrice: 1200000,
    rating: 4.9,
    reviews: 94,
    image: "/images/antieq-corridor.jpg",
    images: [
      "/images/antieq-corridor.jpg",
      "/images/antieq-upper-corridor.jpg",
      "/images/antieq-bedroom2.jpg",
      "/images/antieq-bathroom.jpg",
    ],
    facilities: ["WiFi Fiber", "AC Inverter", "Gym & Pool", "Rooftop Garden", "Coworking Space"],
    available: 3,
    discount: "33%",
    isPopular: true,
    story: "Apartemen mewah dengan pemandangan Teluk Tomini untuk profesional muda yang menghargai kualitas",
    description:
      "ANTIEQ Luxury Suites adalah hunian premium dengan standar apartemen. Menawarkan pemandangan Teluk Tomini yang menakjubkan, fasilitas gym, pool, dan coworking space untuk profesional muda.",
    type: "luxury",
    coordinates: {
      lat: 0.5167,
      lng: 123.2833,
    },
    amenities: [
      "WiFi fiber optic",
      "AC inverter",
      "Swimming pool",
      "Gym 24 jam",
      "Rooftop garden",
      "Coworking space",
      "Meeting room",
      "Cafe",
      "Concierge service",
      "Housekeeping",
      "Valet parking",
      "Sea view",
    ],
    rules: [
      "Profesional/eksekutif muda",
      "Dress code di area publik",
      "Reservasi fasilitas",
      "Quiet hours 22:00-06:00",
      "No smoking in rooms",
      "Maintain cleanliness",
    ],
    contact: {
      phone: "+62 812-3456-7892",
      whatsapp: "+62 812-3456-7892",
      email: "luxury@antieqkost.id",
    },
  },
]

export const reviews: Review[] = [
  {
    id: "1",
    userId: "1",
    propertyId: "1",
    rating: 5,
    comment: "Tempat yang sangat nyaman dan bersih. Fasilitas lengkap dan lokasi strategis. Highly recommended!",
    createdAt: new Date("2024-01-15"),
    user: {
      name: "Siti Nurhaliza",
      avatar: "/placeholder.svg?height=40&width=40&text=SN",
    },
  },
  {
    id: "2",
    userId: "2",
    propertyId: "1",
    rating: 5,
    comment: "Pelayanan excellent, kamar bersih, WiFi kencang. Perfect untuk mahasiswa!",
    createdAt: new Date("2024-01-10"),
    user: {
      name: "Fatimah Zahra",
      avatar: "/placeholder.svg?height=40&width=40&text=FZ",
    },
  },
  {
    id: "3",
    userId: "3",
    propertyId: "2",
    rating: 5,
    comment: "Suasana kekeluargaan yang hangat. Teman-teman di sini sangat supportive.",
    createdAt: new Date("2024-01-08"),
    user: {
      name: "Muhammad Akbar",
      avatar: "/placeholder.svg?height=40&width=40&text=MA",
    },
  },
]

export const locations = [
  { value: "kota-gorontalo", label: "🏙️ Kota Gorontalo", count: 15 },
  { value: "limboto", label: "🌾 Limboto", count: 8 },
  { value: "bone-bolango", label: "🏖️ Bone Bolango", count: 5 },
  { value: "gorontalo-utara", label: "⛰️ Gorontalo Utara", count: 3 },
  { value: "pohuwato", label: "🌴 Pohuwato", count: 2 },
  { value: "boalemo", label: "🏞️ Boalemo", count: 1 },
]

export const kosTypes = [
  { value: "putri", label: "🌸 ANTIEQ Putri Residence", count: 12 },
  { value: "putra", label: "🏢 ANTIEQ Putra Elite", count: 18 },
  { value: "luxury", label: "👑 ANTIEQ Luxury Suites", count: 4 },
]

export const priceRanges = [
  { value: "300k-500k", label: "💰 Rp 300rb - 500rb (Ekonomis)", min: 300000, max: 500000 },
  { value: "500k-800k", label: "💎 Rp 500rb - 800rb (Premium)", min: 500000, max: 800000 },
  { value: "800k-1.2jt", label: "👑 Rp 800rb - 1.2jt (Elite)", min: 800000, max: 1200000 },
  { value: "1.2jt+", label: "🏆 Rp 1.2jt+ (Luxury)", min: 1200000, max: Number.POSITIVE_INFINITY },
]
